#! /bin/sh
#
### BEGIN INIT INFO
# Provides: tomcat
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Starts and stops the Tomcat daemon.
### END INIT INFO

TOMCAT=/var/local/brisskit/onyx/tomcat
STARTUP=$TOMCAT/bin/startup.sh
SHUTDOWN=$TOMCAT/bin/shutdown.sh

export JAVA_OPTS="-Xmx1024M -XX:MaxPermSize=256M"
export JAVA_HOME=/var/local/brisskit/onyx/jdk

start(){
	echo $"Starting Tomcat service: " 
	$STARTUP
	RETVAL=$?
	echo
}

stop(){
	echo $"Stopping Tomcat service: " 
	$SHUTDOWN	
	RETVAL=$?
	echo
}

restart(){
    stop
    sleep 30
    start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
